version: "2.3"

services:
    wrk2:
        build: wrk2
        volumes:
            - ./output:/tmp/results/
            - ./src:/opt/profiler/
        tty: true
    # Sample app is used for simulating request delays.
    sample-app:
        build: sample-app
        volumes:
          - ./sample-app:/usr/src/app
        ports:
          - 80:80
