-- HTTP method, body, and adding a header

wrk.method = "POST"
wrk.body   =[[
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE oxip SYSTEM "oxip.dtd">
<oxip version="6.0">
    <request>
        <reqClientAuth returnToken="N">
            <user>oxiapi</user>
            <password>oxiapi</password>
    </reqClientAuth>
    <reqBetPlace pendingBetCount="Y" returnBalance="Y">
        <token>9eIMbd1ABGUZgkpI5lCV8wURr83MCidSJ5rbvfGgkj/ZnnU3a4Qczv5T4IaaiVgiblAtr26YkZbzpFYnsBOAHCWLn5c3vVlppQpvb08c5YWUjtqWYHbN9p/hdkLunFlM+plpwnOw6s4t</token>
        <errorDetail>ALL</errorDetail>
        <channel>M</channel>
        <fullDetails>Y</fullDetails>
        <clientUserAgent>11</clientUserAgent>
        <bet>
            <betNo>1</betNo>
            <stakePerLine>1</stakePerLine>
            <betType>ACC7</betType>
            <leg>
                <legNo>1</legNo>
                <legSort>--</legSort>
                <legType>W</legType>
                <part>
                    <partNo>1</partNo>
                    <outcome>51813</outcome>
                    <partSort>--</partSort>
                    <priceType>L</priceType>
                    <priceNum>1000</priceNum>
                    <priceDen>1000</priceDen>
                </part>
            </leg>
            <leg>
                <legNo>2</legNo>
                <legSort>--</legSort>
                <legType>W</legType>
                <part>
                    <partNo>1</partNo>
                    <outcome>51821</outcome>
                    <partSort>--</partSort>
                    <priceType>L</priceType>
                    <priceNum>4000</priceNum>
                    <priceDen>1000</priceDen>
                </part>
            </leg>
            <leg>
                <legNo>3</legNo>
                <legSort>--</legSort>
                <legType>W</legType>
                <part>
                    <partNo>1</partNo>
                    <outcome>26740</outcome>
                    <partSort>--</partSort>
                    <priceType>L</priceType>
                    <priceNum>730</priceNum>
                    <priceDen>1000</priceDen>
                </part>
            </leg>
            <leg>
                <legNo>4</legNo>
                <legSort>--</legSort>
                <legType>W</legType>
                <part>
                    <partNo>1</partNo>
                    <outcome>50442</outcome>
                    <partSort>--</partSort>
                    <priceType>L</priceType>
                    <priceNum>11</priceNum>
                    <priceDen>5</priceDen>
                </part>
            </leg>
            <leg>
                <legNo>5</legNo>
                <legSort>--</legSort>
                <legType>W</legType>
                <part>
                    <partNo>1</partNo>
                    <outcome>50450</outcome>
                    <partSort>--</partSort>
                    <priceType>L</priceType>
                    <priceNum>6</priceNum>
                    <priceDen>1</priceDen>
                </part>
            </leg>
            <leg>
                <legNo>6</legNo>
                <legSort>--</legSort>
                <legType>W</legType>
                <part>
                    <partNo>1</partNo>
                    <outcome>50471</outcome>
                    <partSort>--</partSort>
                    <priceType>L</priceType>
                    <priceNum>8</priceNum>
                    <priceDen>1</priceDen>
                </part>
            </leg>
            <leg>
                <legNo>7</legNo>
                <legSort>--</legSort>
                <legType>W</legType>
                <part>
                    <partNo>1</partNo>
                    <outcome>50485</outcome>
                    <partSort>--</partSort>
                    <priceType>L</priceType>
                    <priceNum>25</priceNum>
                    <priceDen>1</priceDen>
                </part>
            </leg>
        </bet> 
    </reqBetPlace>
    </request>
</oxip>
]]
wrk.headers["Content-Type"] = "application/xml"